#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

case ${battery_status} in
  *harging)
    remaining_time=" "$(acpi | sed 's/.*, //;s/ .*//')
    ;;&
  Discharging)
    ;;
  *)
    power=" "
    ;;
esac

format_info "" ${capacity} "${capacity}%${power}${remaining_time}" true
