#!/bin/bash

. "/local/projects/status/lib/status.bash"

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

power=""
if [ ${battery_status} != "Unknown" ]; then
  power=" "
  remaining_time=$(acpi | sed 's/.*, //;s/ .*//')
fi
if [ ${battery_status} != "Discharging" ]; then
  power="  "
fi

format_info "" ${capacity} "${capacity}%${power}${remaining_time}" true
