#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

IFS="
"

stats=$(mpstat 1 1 -P ALL | grep "Average:" | grep -v "CPU")

loads=""
for line in ${stats}; do 
  cpu=$(echo "${line}" | cut -b 14-16)
  idle=$(echo "${line}" | cut -b 91-93)

  load=$((100 - idle))
  if [ ${cpu} == "all" ]; then
    average=${load}
  else
    loads="${loads} $(printf "%3d%%" ${load})"
  fi
done

format_info "" ${average} "[${loads}] $(printf "%3d%%" ${average})"
