#!/bin/bash

. "/local/projects/status/lib/status.bash"

args=(${BLOCK_INSTANCE})
icon=${args[0]}
interface=${args[1]}

if grep "^${interface}" /proc/net/route > /dev/null; then
  format_info "" 0 "${icon}"
else
  format_info "" 100 "${icon}"
fi
