#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

parse_args icon interface signal_command

key_command 3 set_timer

value=0
if grep "^${interface}" /proc/net/route > /dev/null; then
  value=100
  if [ -n "${signal_command}" ]; then
    raw_value=$(${signal_command})
    value=$(scale ${raw_value} 0 31)
    info_string=" ${value}%"
  fi

  if get_timer 5; then
    info_string=" "$(ip addr show ${interface} | \
      grep "    inet " | cut -f 6 -d " ")
  fi
fi

format_info "" ${value} "${icon}${info_string}" true
