#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

parse_args zone

raw_temp=$(cat /sys/class/thermal/thermal_zone${zone}/temp)
temperature=$(echo 1k ${raw_temp} 1000 / p | dc)

format_info "" ${raw_temp} "${temperature}°C" false 0 100000
