#!/bin/bash

. "/local/projects/status/scripts/lib"

raw_temp=$(cat /sys/class/thermal/thermal_zone3/temp)
temperature=$(echo 1k ${raw_temp} 1000 / p | dc)

format_info "" ${raw_temp} "${temperature}°C" false 0 100000
