#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

key_command 3 set_timer

if get_timer 5; then
  info_string=$(uptime -p)
else
  info_string=$(date "+%Y-%m-%d %H:%M:%S")
fi

format_info "" 0 " ${info_string}"
