#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

duration=5

if [ ${BLOCK_BUTTON} == 3 ]; then
  set_timer
fi
if get_timer ${duration}; then
  info_string=$(uptime -p)
else
  info_string=$(date "+%Y-%m-%d %H:%M:%S")
fi

format_info "" 0 " ${info_string}"
