#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

time_file="time_timer.dat"
duration=5

if [ ${BLOCK_BUTTON} == 3 ]; then
  set_timer ${time_file}
fi
if get_timer ${time_file} ${duration}; then
  info_string=$(uptime -p)
else
  info_string=$(date "+%Y-%m-%d %H:%M:%S")
fi

format_info "" 0 " ${info_string}"
