#!/bin/bash

. "/usr/share/i3blocks/status/lib/status.bash"

args=(${BLOCK_INSTANCE})
icon=${args[0]}
interface=${args[1]}

key_launch 1 wicd-client -n
key_command 3 set_timer

essid=$(/sbin/iwgetid -r ${interface})
if [ "${essid}" ]; then
  raw_quality=$(grep "^ ${interface}" /proc/net/wireless | cut -b 16-17)
  quality=$(scale ${raw_quality} 0 70)

  if get_timer 5; then
    info_string=$(ip addr show wlan0 | grep "    inet " | cut -f 6 -d " ")
  else
    info_string="${essid} $(printf "%3d" ${quality})%"
  fi
  format_info "" ${quality} "${icon} ${info_string}" true
else
  format_info "" 100 "${icon}"
fi
